GET http://localhost:8080/api/schedules/all?date=28-10-2022&timeFrom=0:00&timeTo=23:59

###
POST http://localhost:8080/api/reserve/add
Content-Type: application/json

{
  "customerName": "Bob",
  "customerSurname": "Bob",
  "dateAndTime": "28-10-2022 20:10",
  "movieTitle": "ONE PIECE",
  "hallName": "Red 3D",
  "tickets": [
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 1
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 2
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 3
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 4
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 5
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 6
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 7
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 8
      }
    },
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 1,
        "seatNumber": 9
      }
    }
  ]
}

###
POST http://localhost:8080/api/reserve/add
Content-Type: application/json

{
  "customerName": "Bob",
  "customerSurname": "Bob",
  "dateAndTime": "28-10-2022 20:44",
  "hallName": "Red 3D",
  "tickets": [
    {
      "ticketType": "adult",
      "seat": {
        "seatRow": 5,
        "seatNumber": 4
      }
    }
  ]
}