GET http://localhost:8080/api/hall/schedule/1

###
GET http://localhost:8080/api/schedules/all/range?timeFrom=01-01-2022 0:00&timeTo=31-12-2022 23:59

> {%

%}

###
GET http://localhost:8080/api/schedules/all?date=30-10-2022&timeFrom=0:00&timeTo=23:59

> {%
client.log(client.global.get("currentDay"))
%}

